import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
      </head>
      <body className="antialiased min-h-screen relative">
        <div
          className="fixed inset-0 z-[-1] opacity-50 pointer-events-none bg-cover bg-center"
          style={{ backgroundImage: "url(/bumaga.png)" }}
        />
        {children}
      </body>
    </html>
  );
}
